# Generated by Django 5.2 on 2025-04-17 10:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_item_selling_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bought_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='item',
            name='sold',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='itemtransaction',
            name='disputed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
